# Generated by Django 4.2.1 on 2023-06-30 14:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_comment_commented_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="lastupdated",
            field=models.DateField(default=datetime.date(2023, 6, 30)),
        ),
    ]
