# Generated by Django 4.2.1 on 2023-07-04 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_blog_lastupdated"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="username",
            field=models.CharField(default="", max_length=100, null=True),
        ),
    ]
